### ISSUE TITLE
Negative binomial from glm.nb()

### ISSUE THREAD

**Issue by WisamSaleem** [easystats/performance#140]
Hi!
The function check_zeroinflation() is not working when the model is coming from MASS::glm.nb().
Any suggestions, please.

Regards
Wisam

**Comment by strengejacke** [comment]
Thanks, should work now.

**Comment by WisamSaleem** [comment]
Great!
Thank you, it works.

Wisam

**Comment by Camzcamz** [comment]
It is not working on my end when the model is coming from MASS::glm.nb. Here is my code. 

> library("glmmTMB")
> library("MASS")
> data(Salamanders)
> 
> m <- glm(count ~ spp + mined, family = poisson, data = Salamanders)
> check_zeroinflation(m)
# Check for zero-inflation

   Observed zeros: 387
  Predicted zeros: 298
            Ratio: 0.77

Model is underfitting zeros (probable zero-inflation).
> 
> m <- MASS::glm.nb(count ~ spp + mined, data = Salamanders)
> performance::check_zeroinflation(m)
Erreur : Model must be from Poisson-family.
> 
> packageVersion("MASS")
[1] ‘7.3.53’
> packageVersion("performance")
[1] ‘0.4.6’

**Comment by strengejacke** [comment]
Can you try updating your packages?

**Comment by Camzcamz** [comment]
My bad, I just installed the performance package so I thought ti was up to date. I updated the packages and still get the following error. 

> library("glmmTMB")
> library("MASS")
> library("performance")
> data(Salamanders)
> m <- glm(count ~ spp + mined,family = poisson, data = Salamanders)
> check_zeroinflation(m)

   Observed zeros: 387
  Predicted zeros: 298
            Ratio: 0.77

Model is underfitting zeros (probable zero-inflation).
> m <- MASS::glm.nb(count ~ spp + mined, data = Salamanders)
> performance::check_zeroinflation(m)
Erreur : Model must be from Poisson-family.
> packageVersion("MASS")
[1] ‘7.3.53’
> packageVersion("performance")
[1] ‘0.5.1’

**Comment by strengejacke** [comment]
I guess your packages are still not completely up to date, for me, everything works fine.

``` r
library(glmmTMB)
data("Salamanders")

m <- MASS::glm.nb(count ~ spp + mined, data = Salamanders)
performance::check_zeroinflation(m)
#> # Check for zero-inflation
#> 
#>    Observed zeros: 387
#>   Predicted zeros: 374
#>             Ratio: 0.97
#> Model seems ok, ratio of observed and predicted zeros is within the tolerance range.

devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.0.2 (2020-06-22)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  German_Germany.1252         
#>  ctype    German_Germany.1252         
#>  tz       Europe/Berlin               
#>  date     2020-11-04                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package      * version  date       lib source                               
#>  assertthat     0.2.1    2019-03-21 [1] CRAN (R 4.0.0)                       
#>  backports      1.1.10   2020-09-15 [1] CRAN (R 4.0.3)                       
#>  bayestestR     0.7.5.1  2020-10-29 [1] Github (easystats/bayestestR@e7c93c0)
#>  boot           1.3-25   2020-04-26 [2] CRAN (R 4.0.2)                       
#>  callr          3.5.1    2020-10-13 [1] CRAN (R 4.0.3)                       
#>  cli            2.1.0    2020-10-12 [1] CRAN (R 4.0.3)                       
#>  coda           0.19-4   2020-09-30 [1] CRAN (R 4.0.2)                       
#>  codetools      0.2-16   2018-12-24 [2] CRAN (R 4.0.2)                       
#>  crayon         1.3.4    2017-09-16 [1] CRAN (R 4.0.0)                       
#>  desc           1.2.0    2018-05-01 [1] CRAN (R 4.0.0)                       
#>  devtools       2.3.2    2020-09-18 [1] CRAN (R 4.0.2)                       
#>  digest         0.6.27   2020-10-24 [1] CRAN (R 4.0.3)                       
#>  ellipsis       0.3.1    2020-05-15 [1] CRAN (R 4.0.0)                       
#>  emmeans        1.5.2-1  2020-10-25 [1] CRAN (R 4.0.3)                       
#>  estimability   1.3      2018-02-11 [1] CRAN (R 4.0.0)                       
#>  evaluate       0.14     2019-05-28 [1] CRAN (R 4.0.0)                       
#>  fansi          0.4.1    2020-01-08 [1] CRAN (R 4.0.0)                       
#>  fs             1.5.0    2020-07-31 [1] CRAN (R 4.0.2)                       
#>  glmmTMB      * 1.0.2.1  2020-07-02 [1] CRAN (R 4.0.2)                       
#>  glue           1.4.2    2020-08-27 [1] CRAN (R 4.0.2)                       
#>  highr          0.8      2019-03-20 [1] CRAN (R 4.0.0)                       
#>  htmltools      0.5.0    2020-06-16 [1] CRAN (R 4.0.0)                       
#>  insight        0.10.0.1 2020-11-03 [1] local                                
#>  knitr          1.30     2020-09-22 [1] CRAN (R 4.0.2)                       
#>  lattice        0.20-41  2020-04-02 [2] CRAN (R 4.0.2)                       
#>  lme4           1.1-25   2020-10-23 [1] CRAN (R 4.0.3)                       
#>  magrittr       1.5      2014-11-22 [1] CRAN (R 4.0.0)                       
#>  MASS           7.3-51.6 2020-04-26 [2] CRAN (R 4.0.2)                       
#>  Matrix         1.2-18   2019-11-27 [2] CRAN (R 4.0.2)                       
#>  memoise        1.1.0    2017-04-21 [1] CRAN (R 4.0.0)                       
#>  minqa          1.2.4    2014-10-09 [1] CRAN (R 4.0.0)                       
#>  multcomp       1.4-14   2020-09-23 [1] CRAN (R 4.0.2)                       
#>  mvtnorm        1.1-1    2020-06-09 [1] CRAN (R 4.0.0)                       
#>  nlme           3.1-148  2020-05-24 [2] CRAN (R 4.0.2)                       
#>  nloptr         1.2.2.2  2020-07-02 [1] CRAN (R 4.0.2)                       
#>  performance    0.5.1    2020-11-03 [1] local                                
#>  pkgbuild       1.1.0    2020-07-13 [1] CRAN (R 4.0.2)                       
#>  pkgload        1.1.0    2020-05-29 [1] CRAN (R 4.0.0)                       
#>  prettyunits    1.1.1    2020-01-24 [1] CRAN (R 4.0.0)                       
#>  processx       3.4.4    2020-09-03 [1] CRAN (R 4.0.2)                       
#>  ps             1.4.0    2020-10-07 [1] CRAN (R 4.0.2)                       
#>  R6             2.5.0    2020-10-28 [1] CRAN (R 4.0.2)                       
#>  Rcpp           1.0.5    2020-07-06 [1] CRAN (R 4.0.2)                       
#>  remotes        2.2.0    2020-07-21 [1] CRAN (R 4.0.2)                       
#>  rlang          0.4.8    2020-10-08 [1] CRAN (R 4.0.3)                       
#>  rmarkdown      2.5      2020-10-21 [1] CRAN (R 4.0.3)                       
#>  rprojroot      1.3-2    2018-01-03 [1] CRAN (R 4.0.0)                       
#>  sandwich       3.0-0    2020-10-02 [1] CRAN (R 4.0.2)                       
#>  sessioninfo    1.1.1    2018-11-05 [1] CRAN (R 4.0.0)                       
#>  statmod        1.4.35   2020-10-19 [1] CRAN (R 4.0.3)                       
#>  stringi        1.5.3    2020-09-09 [1] CRAN (R 4.0.2)                       
#>  stringr        1.4.0    2019-02-10 [1] CRAN (R 4.0.0)                       
#>  survival       3.1-12   2020-04-10 [2] CRAN (R 4.0.2)                       
#>  testthat       3.0.0    2020-10-31 [1] CRAN (R 4.0.3)                       
#>  TH.data        1.0-10   2019-01-21 [1] CRAN (R 4.0.0)                       
#>  TMB            1.7.18   2020-07-27 [1] CRAN (R 4.0.2)                       
#>  usethis        1.6.3    2020-09-17 [1] CRAN (R 4.0.2)                       
#>  withr          2.2.0    2020-04-20 [1] CRAN (R 4.0.3)                       
#>  xfun           0.19     2020-10-30 [1] CRAN (R 4.0.3)                       
#>  xtable         1.8-4    2019-04-21 [1] CRAN (R 4.0.0)                       
#>  yaml           2.2.1    2020-02-01 [1] CRAN (R 4.0.0)                       
#>  zoo            1.8-8    2020-05-02 [1] CRAN (R 4.0.0)                       
#> 
#> [1] C:/Users/mail/Documents/R/win-library/4.0
#> [2] C:/Program Files/Microsoft/R Open/R-4.0.2/library
```

<sup>Created on 2020-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Camzcamz** [comment]
Thank you. I had to update other packages.
