### ISSUE TITLE
`check_model()` throws error

### ISSUE THREAD

**Issue by hille** [easystats/performance#536]
Hello! It seems that `check_model()` is not working properly:
```
library(easystats)
#defining a model
model <- lm(mpg ~ wt + am + gear + vs * cyl, data = mtcars)

# checking model assumptions
check_model(model)
```
gives me this error message:
```
Variable `Component` is not in your data frame :/
Error: The RStudio 'Plots' window is too small to show this set of plots.
  Please make the window larger.
```
when running with these settings (newest R version and easystats packages fully updated):
```
sessionInfo()
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8   
[3] LC_MONETARY=German_Germany.utf8 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] see_0.7.4          report_0.5.5       parameters_0.20.1  performance_0.10.2
 [5] modelbased_0.8.6   insight_0.18.8     effectsize_0.8.2   datawizard_0.6.5  
 [9] correlation_0.8.3  bayestestR_0.13.0  easystats_0.6.0   

loaded via a namespace (and not attached):
 [1] ggrepel_0.9.2       Rcpp_1.0.9          mvtnorm_1.1-3       lattice_0.20-45    
 [5] tidyr_1.2.1         assertthat_0.2.1    utf8_1.2.2          R6_2.5.1           
 [9] plyr_1.8.8          backports_1.4.1     coda_0.19-4         ggplot2_3.4.0      
[13] pillar_1.8.1        rlang_1.0.6         rstudioapi_0.14     minqa_1.2.5        
[17] car_3.1-1           nloptr_2.0.3        Matrix_1.5-1        labeling_0.4.2     
[21] splines_4.2.2       lme4_1.1-31         stringr_1.5.0       TMB_1.9.1          
[25] afex_1.2-1          munsell_0.5.0       broom_1.0.2         compiler_4.2.2     
[29] numDeriv_2016.8-1.1 pkgconfig_2.0.3     lmerTest_3.1-3      mgcv_1.8-41        
[33] tidyselect_1.2.0    tibble_3.1.8        glmmTMB_1.1.5       fansi_1.0.3        
[37] withr_2.5.0         dplyr_1.0.10        ggpubr_0.5.0        MASS_7.3-58.1      
[41] grid_4.2.2          nlme_3.1-160        xtable_1.8-4        gtable_0.3.1       
[45] lifecycle_1.0.3     DBI_1.1.3           magrittr_2.0.3      scales_1.2.1       
[49] estimability_1.4.1  cli_3.5.0           stringi_1.7.8       carData_3.0-5      
[53] farver_2.1.1        ggsignif_0.6.4      reshape2_1.4.4      generics_0.1.3     
[57] vctrs_0.5.1         boot_1.3-28         tools_4.2.2         glue_1.6.2         
[61] purrr_1.0.1         emmeans_1.8.3       abind_1.4-5         parallel_4.2.2     
[65] colorspace_2.0-3    rstatix_0.7.1       patchwork_1.1.2  
```
but is working with these settings:
```
sessionInfo()
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8    LC_MONETARY=German_Germany.utf8
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] report_0.5.5       see_0.7.3          correlation_0.8.2  modelbased_0.8.5   effectsize_0.7.0.5 parameters_0.18.2 
 [7] performance_0.9.2  bayestestR_0.13.0  datawizard_0.6.1   insight_0.18.4     easystats_0.5.2   

loaded via a namespace (and not attached):
 [1] tidyr_1.2.1         splines_4.2.1       carData_3.0-5       assertthat_0.2.1    yaml_2.3.5         
 [6] ggrepel_0.9.1       numDeriv_2016.8-1.1 pillar_1.8.1        backports_1.4.1     lattice_0.20-45    
[11] glue_1.6.2          digest_0.6.29       ggsignif_0.6.4      glmmTMB_1.1.4       minqa_1.2.4        
[16] colorspace_2.0-3    htmltools_0.5.3     Matrix_1.5-1        plyr_1.8.7          pkgconfig_2.0.3    
[21] broom_1.0.1         purrr_0.3.4         xtable_1.8-4        mvtnorm_1.1-3       patchwork_1.1.2    
[26] scales_1.2.1        lme4_1.1-30         emmeans_1.8.1-1     tibble_3.1.8        mgcv_1.8-40        
[31] farver_2.1.1        generics_0.1.3      car_3.1-0           ggplot2_3.3.6       ggpubr_0.4.0       
[36] TMB_1.9.1           cli_3.4.1           magrittr_2.0.3      estimability_1.4.1  evaluate_0.16      
[41] fansi_1.0.3         nlme_3.1-157        MASS_7.3-57         rstatix_0.7.0       tools_4.2.1        
[46] lifecycle_1.0.2     stringr_1.4.1       munsell_0.5.0       compiler_4.2.1      rlang_1.0.6        
[51] grid_4.2.1          nloptr_2.0.3        rstudioapi_0.14     labeling_0.4.2      rmarkdown_2.16     
[56] boot_1.3-28         gtable_0.3.1        lmerTest_3.1-3      abind_1.4-5         DBI_1.1.3          
[61] reshape2_1.4.4      R6_2.5.1            knitr_1.40          dplyr_1.0.10        afex_1.1-1         
[66] fastmap_1.1.0       utf8_1.2.2          stringi_1.7.8       parallel_4.2.1      Rcpp_1.0.9         
[71] vctrs_0.4.1         tidyselect_1.1.2    xfun_0.33           coda_0.19-4 
```

**Comment by ibrila** [comment]
I'm having the same issue:

`sessionInfo()
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.utf8  LC_CTYPE=English_United Kingdom.utf8    LC_MONETARY=English_United Kingdom.utf8 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] sessioninfo_1.2.2   see_0.7.4           report_0.5.5        parameters_0.20.1   modelbased_0.8.5    insight_0.18.8      effectsize_0.8.2    datawizard_0.6.5   
 [9] correlation_0.8.3   bayestestR_0.13.0   easystats_0.6.0     MetBrewer_0.2.0     patchwork_1.1.2     bestNormalize_1.8.3 ggeffects_1.1.4     sandwich_3.0-2     
[17] relaimpo_2.2-6      mitools_2.4         survey_4.1-1        survival_3.5-0      boot_1.3-28.1       MASS_7.3-58.1       MuMIn_1.47.1        performance_0.10.1 
[25] lubridate_1.9.0     timechange_0.2.0    microbiome_1.18.0   lmerTest_3.1-3      lme4_1.1-31         Matrix_1.5-3        sjPlot_2.8.12       rbiom_1.0.3        
[33] vegan_2.6-4         lattice_0.20-45     permute_0.9-7       phyloseq_1.40.0     ggforce_0.4.1       rcompanion_2.4.18   corrr_0.4.4         ggcorrplot_0.1.4   
[41] qiime2R_0.99.6      decontam_1.16.0     tidylog_1.0.2       magrittr_2.0.3      reactable_0.4.3     scales_1.2.1        plotly_4.10.1       skimr_2.1.5        
[49] janitor_2.1.0       forcats_0.5.2       stringr_1.5.0       dplyr_1.0.10        purrr_1.0.1         readr_2.1.3         tidyr_1.2.1         tibble_3.1.8       
[57] ggplot2_3.4.0       tidyverse_1.3.2    

loaded via a namespace (and not attached):
  [1] estimability_1.4.1     coda_0.19-4            knitr_1.41             multcomp_1.4-20        data.table_1.14.6      rpart_4.1.19           hardhat_1.2.0         
  [8] RCurl_1.98-1.9         doParallel_1.0.17      generics_0.1.3         BiocGenerics_0.42.0    TH.data_1.1-1          proxy_0.4-27           future_1.30.0         
 [15] tzdb_0.3.0             xml2_1.3.3             assertthat_0.2.1       gargle_1.2.1           relimp_1.0-5           gower_1.0.1            xfun_0.36             
 [22] hms_1.1.2              DEoptimR_1.0-11        fansi_1.0.3            dbplyr_2.2.1           readxl_1.4.1           igraph_1.3.5           DBI_1.1.3             
 [29] htmlwidgets_1.6.1      googledrive_2.0.0      stats4_4.2.1           ellipsis_0.3.2         backports_1.4.1        picante_1.8.2          RcppParallel_5.1.6    
 [36] libcoin_1.0-9          deldir_1.0-6           vctrs_0.5.1            Biobase_2.56.0         abind_1.4-5            sjlabelled_1.2.0       withr_2.5.0           
 [43] robustbase_0.95-0      RcmdrMisc_2.7-2        checkmate_2.1.0        emmeans_1.8.3          cluster_2.1.4          ape_5.6-2              lazyeval_0.2.2        
 [50] crayon_1.5.2           labeling_0.4.2         recipes_1.0.4          pkgconfig_2.0.3        zCompositions_1.4.0-1  slam_0.1-50            tweenr_2.0.2          
 [57] GenomeInfoDb_1.32.4    Rcmdr_2.8-0            nlme_3.1-161           nnet_7.3-18            globals_0.16.2         rlang_1.0.6            lifecycle_1.0.3       
 [64] modelr_0.1.10          tcltk_4.2.1            cellranger_1.1.0       polyclip_1.10-4        matrixStats_0.63.0     lmtest_0.9-40          rngtools_1.5.2        
 [71] carData_3.0-5          BiodiversityR_2.15-1   Rhdf5lib_1.18.2        zoo_1.8-11             reprex_2.0.2           base64enc_0.1-3        googlesheets4_1.0.1   
 [78] png_0.1-8              viridisLite_0.4.1      clisymbols_1.2.0       rootSolve_1.8.2.3      bitops_1.0-7           rhdf5filters_1.8.0     Biostrings_2.64.1     
 [85] qqplotr_0.0.5          doRNG_1.8.3            multcompView_0.1-8     parallelly_1.33.0      coin_1.4-2             jpeg_0.1-10            S4Vectors_0.34.0      
 [92] plyr_1.8.8             zlibbioc_1.42.0        compiler_4.2.1         RColorBrewer_1.1-3     snakecase_0.11.0       cli_3.6.0              ade4_1.7-20           
 [99] XVector_0.36.0         listenv_0.9.0          htmlTable_2.4.1        Formula_1.2-4          mgcv_1.8-41            tidyselect_1.2.0       tcltk2_1.2-11         
[106] stringi_1.7.12         butcher_0.3.1          yaml_2.3.6             ggrepel_0.9.2          latticeExtra_0.6-30    tools_4.2.1            lmom_2.9              
[113] future.apply_1.10.0    parallel_4.2.1         rstudioapi_0.14        foreach_1.5.2          foreign_0.8-84         gridExtra_2.3          gld_2.6.6             
[120] prodlim_2019.11.13     farver_2.1.1           Rtsne_0.16             digest_0.6.31          lava_1.7.1             nortest_1.0-4          Rcpp_1.0.9            
[127] car_3.1-1              broom_1.0.2            httr_1.4.4             effects_4.2-2          sjstats_0.18.2         colorspace_2.0-3       rvest_1.0.3           
[134] fs_1.5.2               IRanges_2.30.1         truncnorm_1.0-8        splines_4.2.1          expm_0.999-7           multtest_2.52.0        Exact_3.2             
[141] xtable_1.8-4           jsonlite_1.8.4         nloptr_2.0.3           corpcor_1.6.10         timeDate_4022.108      modeltools_0.2-23      ipred_0.9-13          
[148] R6_2.5.1               Hmisc_4.7-2            NADA_1.6-1.1           pillar_1.8.1           htmltools_0.5.4        glue_1.6.2             fastmap_1.1.0         
[155] minqa_1.2.5            DT_0.26                class_7.3-20           codetools_0.2-18       mvtnorm_1.1-3          utf8_1.2.2             numDeriv_2016.8-1.1   
[162] DescTools_0.99.47      interp_1.1-3           repr_1.1.4             biomformat_1.24.0      munsell_0.5.0          e1071_1.7-12           rhdf5_2.40.0          
[169] GenomeInfoDbData_1.2.8 iterators_1.0.14       sjmisc_2.8.9           haven_2.5.1            reshape2_1.4.4         gtable_0.3.1          `

**Comment by mattansb** [comment]
You need to make sure your plot window in RStudio is big enough.

**Comment by mattansb** [comment]
Can you share you screen resolution?

**Comment by hille** [comment]
Sure, it is 3840 x 2160.

**Comment by hille** [comment]
I changed the resolution to 1920 x 1080 and it worked! Is this a problem of RStudio then?

**Comment by mattansb** [comment]
Seems like it - super weird tho...

**Comment by hille** [comment]
Yes, all other plots work like a charm (e.g. `plot(check_normality()`)... Thanks for your help!

**Comment by bwiernik** [comment]
Clicking the Zoom button in the RStudio Plots pane should generally resolve any issues with the Plots pane not playing well with the grid graphics package

**Comment by hille** [comment]
When I click on the zoom button, a blank window opens.

**Comment by etiennebacher** [comment]
> > Variable `Component` is not in your data frame :/
> 
> Why do we get this warning?

Comes from here: 

https://github.com/easystats/performance/blob/9714a2a4e75785d03eb77e400da9dc50e64d2fa7/R/check_model_diagnostics.R#L13-L18

By the way, `datawizard::data_rename()` doesn't have a `verbose` arg in `0.6.5`, it's only available in the current devel version.

**Comment by strengejacke** [comment]
Yes, I think this is already fixed.

**Comment by strengejacke** [comment]
Strange, works fine for me even with RStudio.


https://user-images.githubusercontent.com/26301769/213260282-a7c0108b-4b98-42bd-8365-1ecfbe23847d.mp4

``` r
library(easystats)
#> # Attaching packages: easystats 0.6.0.5
#> ✔ bayestestR  0.13.0.5   ✔ correlation 0.8.3   
#> ✔ datawizard  0.6.5.4    ✔ effectsize  0.8.2.6 
#> ✔ insight     0.18.8.9   ✔ modelbased  0.8.6.1 
#> ✔ performance 0.10.2.2   ✔ parameters  0.20.1.1
#> ✔ report      0.5.5.3    ✔ see         0.7.4.2
#defining a model
model <- lm(mpg ~ wt + am + gear + vs * cyl, data = mtcars)

# checking model assumptions
check_model(model)
```

![](https://i.imgur.com/OwSa4mk.png)

``` r

sessionInfo()
#> R version 4.2.2 (2022-10-31 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19045)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8   
#> [3] LC_MONETARY=German_Germany.utf8 LC_NUMERIC=C                   
#> [5] LC_TIME=German_Germany.utf8    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#>  [1] see_0.7.4.2          report_0.5.5.3       parameters_0.20.1.1 
#>  [4] performance_0.10.2.2 modelbased_0.8.6.1   insight_0.18.8.9    
#>  [7] effectsize_0.8.2.6   datawizard_0.6.5.4   correlation_0.8.3   
#> [10] bayestestR_0.13.0.5  easystats_0.6.0.5   
#> 
#> loaded via a namespace (and not attached):
#>  [1] splines_4.2.2      R.utils_2.12.2     assertthat_0.2.1   highr_0.10        
#>  [5] yaml_2.3.6         robustbase_0.95-0  ggrepel_0.9.2      pillar_1.8.1      
#>  [9] lattice_0.20-45    glue_1.6.2         digest_0.6.31      colorspace_2.0-3  
#> [13] sandwich_3.0-2     htmltools_0.5.4    Matrix_1.5-3       R.oo_1.25.0       
#> [17] pkgconfig_2.0.3    purrr_1.0.1        xtable_1.8-4       mvtnorm_1.1-3     
#> [21] patchwork_1.1.2    scales_1.2.1       emmeans_1.8.3      tibble_3.1.8      
#> [25] mgcv_1.8-41        styler_1.9.0       farver_2.1.1       generics_0.1.3    
#> [29] ggplot2_3.4.0      TH.data_1.1-1      withr_2.5.0        cli_3.6.0         
#> [33] survival_3.5-0     magrittr_2.0.3     estimability_1.4.1 evaluate_0.19     
#> [37] R.methodsS3_1.8.2  fs_1.5.2           fansi_1.0.3        nlme_3.1-160      
#> [41] R.cache_0.16.0     MASS_7.3-58.1      tools_4.2.2        lifecycle_1.0.3   
#> [45] multcomp_1.4-20    stringr_1.5.0      munsell_0.5.0      reprex_2.0.2      
#> [49] qqplotr_0.0.5      compiler_4.2.2     rlang_1.0.6        grid_4.2.2        
#> [53] rstudioapi_0.14    labeling_0.4.2     rmarkdown_2.19     gtable_0.3.1      
#> [57] codetools_0.2-18   DBI_1.1.3          R6_2.5.1           zoo_1.8-11        
#> [61] knitr_1.41         dplyr_1.0.10       fastmap_1.1.0      utf8_1.2.2        
#> [65] stringi_1.7.12     Rcpp_1.0.9         vctrs_0.5.1        DEoptimR_1.0-11   
#> [69] tidyselect_1.2.0   xfun_0.36          coda_0.19-4
```

<sup>Created on 2023-01-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by king0708** [comment]
Same error message/issue with the plot window being too small even if I open the plot zoom and make it as big as possible. I used to love this package but I can never figure out how to actually use check_model() because of this issue. 

R version 4.3.0 (2023-04-21 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] lmerTest_3.1-3      officer_0.6.2       flextable_0.9.1     gt_0.9.0           
 [5] cowplot_1.1.1       boot_1.3-28.1       sjPlot_2.8.14       DHARMa_0.4.6       
 [9] glmmTMB_1.1.7       ggrepel_0.9.3       knitr_1.42          bayestestR_0.13.1  
[13] emmeans_1.8.5       lme4_1.1-32         Matrix_1.5-4        performance_0.10.3 
[17] fitdistrplus_1.1-11 survival_3.5-5      MASS_7.3-59         broom_1.0.4        
[21] ggpubr_0.6.0        xtable_1.8-4        kableExtra_1.3.4    extrafont_0.19     
[25] quantreg_5.95       SparseM_1.81        rcompanion_2.4.30   readxl_1.4.2       
[29] lubridate_1.9.2     forcats_1.0.0       stringr_1.5.0       dplyr_1.1.2        
[33] purrr_1.0.1         readr_2.1.4         tidyr_1.3.0         tibble_3.2.1       
[37] ggplot2_3.4.2       tidyverse_2.0.0    

loaded via a namespace (and not attached):
  [1] splines_4.3.0           later_1.3.0             cellranger_1.1.0       
  [4] datawizard_0.7.1        polyclip_1.10-4         rpart_4.1.19           
  [7] lifecycle_1.0.3         rstatix_0.7.2           lattice_0.21-8         
 [10] insight_0.19.1          backports_1.4.1         magrittr_2.0.3         
 [13] Hmisc_5.0-1             rmarkdown_2.21          httpuv_1.6.9           
 [16] zip_2.3.0               askpass_1.1             gld_2.6.6              
 [19] minqa_1.2.5             multcomp_1.4-23         abind_1.4-5            
 [22] rvest_1.0.3             expm_0.999-7            nnet_7.3-18            
 [25] TH.data_1.1-2           tweenr_2.0.2            sandwich_3.0-2         
 [28] gdtools_0.3.3           crul_1.3                nortest_1.0-4          
 [31] MatrixModels_0.5-1      svglite_2.1.1           codetools_0.2-19       
 [34] coin_1.4-2              ggforce_0.4.1           xml2_1.3.3             
 [37] tidyselect_1.2.0        farver_2.1.1            ggeffects_1.2.1        
 [40] httpcode_0.3.0          viridis_0.6.2           matrixStats_0.63.0     
 [43] stats4_4.3.0            base64enc_0.1-3         webshot_0.5.4          
 [46] jsonlite_1.8.4          e1071_1.7-13            ellipsis_0.3.2         
 [49] Formula_1.2-5           systemfonts_1.0.4       tools_4.3.0            
 [52] ragg_1.2.5              DescTools_0.99.49       Rcpp_1.0.10            
 [55] glue_1.6.2              gridExtra_2.3           Rttf2pt1_1.3.12        
 [58] mgcv_1.8-42             xfun_0.39               withr_2.5.0            
 [61] numDeriv_2016.8-1.1     fastmap_1.1.1           fansi_1.0.4            
 [64] openssl_2.0.6           digest_0.6.31           timechange_0.2.0       
 [67] R6_2.5.1                mime_0.12               estimability_1.4.1     
 [70] textshaping_0.3.6       colorspace_2.1-0        see_0.7.5              
 [73] utf8_1.2.3              generics_0.1.3          fontLiberation_0.1.0   
 [76] data.table_1.14.8       class_7.3-21            httr_1.4.5             
 [79] htmlwidgets_1.6.2       pkgconfig_2.0.3         gtable_0.3.3           
 [82] Exact_3.2               modeltools_0.2-23       lmtest_0.9-40          
 [85] htmltools_0.5.5         fontBitstreamVera_0.1.1 carData_3.0-5          
 [88] TMB_1.9.4               multcompView_0.1-9      scales_1.2.1           
 [91] lmom_2.9                rstudioapi_0.14         tzdb_0.3.0             
 [94] uuid_1.1-0              checkmate_2.1.0         nlme_3.1-162           
 [97] curl_5.0.0              nloptr_2.0.3            proxy_0.4-27           
[100] zoo_1.8-12              sjlabelled_1.2.0        rootSolve_1.8.2.3      
[103] parallel_4.3.0          libcoin_1.0-9           foreign_0.8-84         
[106] pillar_1.9.0            grid_4.3.0              vctrs_0.6.2            
[109] promises_1.2.0.1        car_3.1-2               cluster_2.1.4          
[112] extrafontdb_1.0         htmlTable_2.4.1         evaluate_0.20          
[115] mvtnorm_1.1-3           cli_3.6.1               compiler_4.3.0         
[118] rlang_1.1.0             crayon_1.5.2            ggsignif_0.6.4         
[121] labeling_0.4.2          modelr_0.1.11           plyr_1.8.8             
[124] sjmisc_2.8.9            stringi_1.7.12          viridisLite_0.4.1      
[127] munsell_0.5.0           fontquiver_0.2.1        sjstats_0.18.2         
[130] patchwork_1.1.2         hms_1.1.3               gfonts_0.2.0           
[133] shiny_1.7.4

**Comment by bwiernik** [comment]
What version of RStudio are you using, and do you encounter the problem if you use R GUI instead?

**Comment by king0708** [comment]
R version 4.3.0, RStudio version 2023.03.1. No issues when I run the following code in the R Gui, but I still get the same error if I run in RStudio no matter how big I make the viewer window on my laptop or if I open the plot zoom. 

`data(mtcars)`
`mod <- lm(mpg ~ disp + cyl, data = mtcars)`
`performance::check_model(mod)`

**Comment by popovs** [comment]
Same issue here in RStudio version 2023.03.1. It seems to be specific to `lm` and `lmer` models - works just fine with `glmmTMB` models.

```
R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS 13.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] lme4_1.1-29       Matrix_1.3-4      viridis_0.6.2    
 [4] viridisLite_0.4.0 sf_1.0-12         dplyr_1.1.1      
 [7] ggplot2_3.4.2     mgcv_1.8-42       nlme_3.1-153     
[10] glmmTMB_1.1.7    

loaded via a namespace (and not attached):
  [1] readxl_1.4.2        backports_1.4.1     plyr_1.8.7         
  [4] sp_1.6-0            TMB_1.9.3           splines_4.1.2      
  [7] listenv_0.8.0       gap.datasets_0.0.5  TH.data_1.1-1      
 [10] digest_0.6.29       foreach_1.5.1       gratia_0.8.1       
 [13] htmltools_0.5.5     fansi_1.0.4         magrittr_2.0.3     
 [16] DHARMa_0.4.6        doParallel_1.0.16   see_0.7.5          
 [19] globals_0.16.1      modelr_0.1.8        matrixStats_0.61.0 
 [22] sandwich_3.0-2      exactextractr_0.9.1 MAMU_0.2.0         
 [25] bdsmatrix_1.3-6     timechange_0.2.0    beepr_1.3          
 [28] colorspace_2.0-3    ggrepel_0.9.3       mitools_2.4        
 [31] xfun_0.31           crayon_1.5.2        iterators_1.0.13   
 [34] survival_3.2-13     zoo_1.8-10          glue_1.6.2         
 [37] polyclip_1.10-0     gtable_0.3.0        emmeans_1.8.5      
 [40] sjstats_0.18.2      sjmisc_2.8.9        scales_1.2.0       
 [43] mvtnorm_1.1-3       DBI_1.1.3           GGally_2.1.2       
 [46] ggeffects_1.2.0     miniUI_0.1.1.1      Rcpp_1.0.10        
 [49] xtable_1.8-4        performance_0.10.3  units_0.8-1        
 [52] proxy_0.4-27        stats4_4.1.2        survey_4.1-1       
 [55] datawizard_0.7.1    RColorBrewer_1.1-3  ellipsis_0.3.2     
 [58] wk_0.7.2            pkgconfig_2.0.3     reshape_0.8.9      
 [61] farver_2.1.0        qgam_1.3.4          nnet_7.3-16        
 [64] utf8_1.2.3          janitor_2.2.0       later_1.3.0        
 [67] tidyselect_1.2.0    labeling_0.4.2      rlang_1.1.0        
 [70] munsell_0.5.0       cellranger_1.1.0    tools_4.1.2        
 [73] cli_3.6.1           generics_0.1.3      audio_0.1-10       
 [76] sjlabelled_1.2.0    broom_0.8.0         evaluate_0.15      
 [79] stringr_1.5.0       fastmap_1.1.0       yaml_2.3.5         
 [82] knitr_1.39          purrr_1.0.1         s2_1.1.2           
 [85] future_1.28.0       mime_0.12           mvnfast_0.2.8      
 [88] gap_1.5-1           compiler_4.1.2      rstudioapi_0.13    
 [91] gamm4_0.2-6         e1071_1.7-13        tibble_3.2.1       
 [94] tweenr_1.0.2        stringi_1.7.12      forcats_0.5.1      
 [97] lattice_0.20-45     classInt_0.4-9      nloptr_2.0.3       
[100] vctrs_0.6.1         effects_4.2-2       pillar_1.9.0       
[103] lifecycle_1.0.3     furrr_0.3.1         estimability_1.4.1 
[106] insight_0.19.1      raster_3.6-20       httpuv_1.6.3       
[109] patchwork_1.1.2     R6_2.5.1            promises_1.2.0.1   
[112] KernSmooth_2.23-20  gridExtra_2.3       parallelly_1.32.1  
[115] codetools_0.2-18    boot_1.3-28         MASS_7.3-54        
[118] withr_2.5.0         multcomp_1.4-20     broom.mixed_0.2.9.4
[121] bayestestR_0.13.0   parallel_4.1.2      terra_1.7-18       
[124] grid_4.1.2          sjPlot_2.8.13       mgcViz_0.1.9       
[127] tidyr_1.3.0         coda_0.19-4         class_7.3-19       
[130] minqa_1.2.4         rmarkdown_2.14      snakecase_0.11.0   
[133] carData_3.0-5       bbmle_1.0.25        ggforce_0.3.3      
[136] shiny_1.7.1         numDeriv_2016.8-1.1 lubridate_1.9.2   
```

**Comment by strengejacke** [comment]
Hm, strange, I have no such issues:

https://github.com/easystats/performance/assets/26301769/02924775-c92e-4be6-96ef-dad48bb3ff45

Can you please install the latest version from _see_? (make sure you have version 0.7.5.7, i.e. this version needs to be on r-universe, which you can check here: https://github.com/easystats/see#installation). Simply run following code line:

```r
easystats::install_latest(force = TRUE)
```

then run (note the `debug = TRUE`):

```r
data(mtcars)
mod <- lm(mpg ~ disp + cyl, data = mtcars)
see::plot(performance::check_model(mod), debug = TRUE)
```

Can you post the error message?

**Comment by hille** [comment]
Hello! I tried to run the code and it gives me this
```
see::plot(performance::check_model(mod), debug = TRUE)
Error: 'plot' is not an exported object from 'namespace:see'
```

For me it seems to be an issue of screen resolution since `check_model(mod)` does not work with 3840 x 2160 (giving the error messages that were postet above), but works immediatly after I change to e.g. 1920 x 1080.

**Comment by hille** [comment]
Okay, another interesting thing: It does not work with 3840 x 2160 using 250% scaling, but works with 200% scaling (system recommendation would be 300% which also does not work).
![image](https://github.com/easystats/performance/assets/28395806/cbdd5088-24f3-40de-b1e6-9ef04e3b3d26)

**Comment by strengejacke** [comment]
Sorry, it was meant to be`plot(performance::check_model(mod), debug = TRUE)`, without `see::`.

**Comment by hille** [comment]
```
> plot(performance::check_model(mod), debug = TRUE)
For confidence bands, please install `qqplotr`.

Following error was thrown: The RStudio 'Plots' window may be too small to show this patchwork.

  Please make the window larger. 

Error: The RStudio 'Plots' window is too small to show this set of plots.
  Please make the window larger.
  ```

**Comment by strengejacke** [comment]
Ok, that error is not more informative than our error message. But I can now reproduce your issue, I think the scaling in the graphic/display settings is indeed the problem here:

> Okay, another interesting thing: It does not work with 3840 x 2160 using 250% scaling, but works with 200% scaling (system recommendation would be 300% which also does not work).

My PC offers scaling from 100% to 175% and with 125%, I already get this error when the plot-window is too small.

https://github.com/easystats/performance/assets/26301769/16ffd2e6-8c53-4c38-81a8-7cbea6b8fc81

**Comment by strengejacke** [comment]
It _seems_ to me that this is an RStudio issue in combination with scaled interface (see comments above). I opened a discussion thread at the Posit-forums, let's see whether this clarifies this issue (https://community.rstudio.com/t/rstudio-fails-to-display-plots-in-particular-with-rescaled-apps-display-settings/167054).

**Comment by popovs** [comment]
Yep, that solved the problem! My eyes are terrible so my default RStudio sessions are zoomed in. `View > Actual Size` fixed it for me. Perhaps updating the error message to suggest rescaling your RStudio session to 'Actual Size' (`Ctrl/Cmd + 0`) will help?

**Comment by strengejacke** [comment]
Thanks a lot for debugging this issue. I think the only thing we can do is giving an informative error message, we probably can't fix this issue from our end (but we'll keep looking into this). This is what currently is displayed when this issue arises:

![image](https://github.com/easystats/performance/assets/26301769/c1dd92fb-8e0a-4e0c-9995-60b78ba423de)

**Comment by strengejacke** [comment]
@thomasp85 This happens when we compose a set of plots using _patchwork_ - that's why I'm tagging you here. To summarize the thread:

1. We have a function, `performance::check_model()`, that produces a number of diagnostic plots. These are composed using the _patchwork_ package
2. If either zoom in RStudio (https://github.com/easystats/performance/issues/536#issuecomment-1572950444) or scale/zoom for apps as a system setting (https://github.com/easystats/performance/issues/536#issuecomment-1564163228) is increased, the plot no longer appears, but an error shows up:

> Following error was thrown: The RStudio 'Plots' window may be too small to show this patchwork.

Not sure if this is related to the _patchwork_ package or not, but maybe you have an idea how to fix this?

**Comment by thomasp85** [comment]
It is only partly because of patchwork. The issue comes because there is not enough area for the plot elements as you zoom in and this is exasperated by putting more plot elements in the plot with patchwork. Some elements in a ggplot2 plot have absolute sizes, e.g. all text elements and by extensions the areas that are defined to have enough space for these elements (titles, axes, etc). As you zoom, these absolute areas increase in size and at some point there is simple not enough room in the plot area to contain them all, which is when you get this error.

**Comment by strengejacke** [comment]
thanks for the explanation! So the current "fix" would indeed be that users reduce the scaling factor, either in RStudio or their system settings?

**Comment by thomasp85** [comment]
yes, or decrease the size of their absolute elements by e.g. decreasing the base font size of the theme

**Comment by strengejacke** [comment]
Thanks, this is what now is printed:

![image](https://github.com/easystats/performance/assets/26301769/03ce255c-91d4-4d22-b513-2f69e5f490f3)

Since the error occurs _before_ we could possibly change base font size, we leave it to the user to try one of the possible solutions to this problem. Closing this issue.

**Comment by jbohenek** [comment]
I primarily work in Rmarkdown/Quarto documents. If anyone is having this issue in Rmarkdown/Quarto documents and they display chunk output inline (as opposed to the console), you can simply adjust the chunk properties. `{r fig.height=8, fig.wdith=7}` seems to work well for me most of the time to get everything to fit and display well.
