### ISSUE TITLE
ICC for multiple membership model

### ISSUE THREAD

**Issue by PiaKre** [easystats/performance#77]
I'm trying to estimate the ICC for a multiple membership model estimated with brms. There are students (level 1) nested in teachers (T1_ID, level 2) and classrooms (C1_ID, also level 2). I get an estimate if I condition on all random effects, that is not specifying re.form. However, I'd like to get estimates for the two level 2 effects separately. Is there a way to do this with the performance package? When I tried I got the error message: 

> Error in is(sexpr, "try-error") : argument "sexpr" is missing, with no default

My model is
`Fixed.FAPs.int.fixed <- brm(PFixedT3 ~ 0 + Intercept + (0 + Intercept |p| mm(T1_ID, T2_ID, T3_ID, T4_ID, weights = cbind(W_T1, W_T2, W_T3, W_T4))) + (0 + Intercept |q| mm(C1_ID, C2_ID, C3_ID, C4_ID, weights = cbind(W_C1, W_C2, W_C3, W_C4))), family = skew_normal(), data=data_fixed, control = list(adapt_delta = 0.99), inits = 0, cores = 4)`

and for the ICC for teachers

`icc(Fixed.FAPs.int.fixed, re.form = ~ (0 + Intercept |p| mm(T1_ID, T2_ID, T3_ID, T4_ID, weights = cbind(W_T1, W_T2, W_T3, W_T4))))`

Any ideas? Thanks

**Comment by strengejacke** [comment]
Not sure if I fixed it in between, but can you try update _insight_ from GitHub? Then it might work:

``` r
m <- insight::download_model("brms_mm_1")
performance::icc(m)
#> # Random Effect Variances and ICC
#> 
#> Conditioned on: all random effects
#> 
#> ## Variance Ratio (comparable to ICC)
#> Ratio: 0.02  CI 95%: [-0.22 0.22]
#> 
#> ## Variances of Posterior Predicted Distribution
#> Conditioned on fixed effects: 62.43  CI 95%: [49.53 78.01]
#> Conditioned on rand. effects: 63.55  CI 95%: [50.55 80.11]
#> 
#> ## Difference in Variances
#> Difference: 1.14  CI 95%: [-12.78 15.98]
```

<sup>Created on 2019-08-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
Oh, and `brms_mm_1` is a [multimembership-model](https://easystats.github.io/circus/reference/brms_mm_1.html).

**Comment by strengejacke** [comment]
_bump_

**Comment by PiaKre** [comment]
Sorry, I completely missed your previous response. I updated the insight package but still get the same error message.

**Comment by strengejacke** [comment]
Hm. Do you have a small, reproducible example?

**Comment by PiaKre** [comment]
I can make one but am on holidays at the moment. I'll get back to you after. Thank you

**Comment by strengejacke** [comment]
Great, thanks! Enjoy your holidays!

**Comment by PiaKre** [comment]
Thanks :)

**Comment by PiaKre** [comment]
Hi, back home now. 
Here is a small subset of my data and the code in a pdf. Hope this helps. 
[Reproducible Example.pdf](https://github.com/easystats/performance/files/3635497/Reproducible.Example.pdf)
[d_subset.xlsx](https://github.com/easystats/performance/files/3635500/d_subset.xlsx)
